# Generated by Django 5.0 on 2023-12-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssestTransportationRequest',
            new_name='AssetTransportationRequest',
        ),
    ]
