# Generated by Django 5.0 on 2023-12-06 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0004_rider_travel_medium_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('asset_capacity', models.IntegerField()),
                ('travel_date', models.DateField()),
                ('travel_medium', models.CharField(choices=[('Car', 'Car'), ('Bus', 'Bus'), ('Train', 'Train')], max_length=100)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='assettransportationrequest',
            name='matched_riders',
            field=models.ManyToManyField(related_name='matched_requests', to='ride_sharing.ride'),
        ),
        migrations.DeleteModel(
            name='Rider',
        ),
    ]
