# Generated by Django 5.0 on 2023-12-07 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0006_alter_assettransportationrequest_requester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assettransportationrequest',
            name='matched_riders',
        ),
        migrations.CreateModel(
            name='MatchedRides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_APPLIED', 'Not Applied'), ('APPLIED', 'Applied')], default='NOT_APPLIED', max_length=100)),
                ('asset_transportation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride_sharing.assettransportationrequest')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride_sharing.ride')),
            ],
        ),
    ]
