# Generated by Django 5.0 on 2023-12-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0007_remove_assettransportationrequest_matched_riders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettransportationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('EXPIRED', 'Expired')], default='PENDING', max_length=100),
        ),
    ]
